-- MySQL Script generated by MySQL Workbench
-- Mon May  4 09:45:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestionRecettes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GestionRecettes` ;

-- -----------------------------------------------------
-- Schema GestionRecettes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestionRecettes` DEFAULT CHARACTER SET utf8 ;
USE `GestionRecettes` ;

-- -----------------------------------------------------
-- Table `GestionRecettes`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionRecettes`.`users` ;

CREATE TABLE IF NOT EXISTS `GestionRecettes`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NULL,
  `firstCon` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionRecettes`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionRecettes`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `GestionRecettes`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionRecettes`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionRecettes`.`categories` ;

CREATE TABLE IF NOT EXISTS `GestionRecettes`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionRecettes`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionRecettes`.`recipes` ;

CREATE TABLE IF NOT EXISTS `GestionRecettes`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `prepareTime` INT NOT NULL,
  `cookTime` INT NOT NULL,
  `portion` INT NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `moyNote` DECIMAL NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_recipes_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `GestionRecettes`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionRecettes`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionRecettes`.`reviews` ;

CREATE TABLE IF NOT EXISTS `GestionRecettes`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_recipes1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `GestionRecettes`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionRecettes`.`recipes_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionRecettes`.`recipes_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `GestionRecettes`.`recipes_has_ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `unity` VARCHAR(45) NOT NULL,
  `recipe_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_has_ingredients_ingredients1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_recipes_has_ingredients_recipes1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipes_has_ingredients_recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `GestionRecettes`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipes_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `GestionRecettes`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
